/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quantlib_FXOption */

#ifndef _Included_com_quantlib_FXOption
#define _Included_com_quantlib_FXOption
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quantlib_FXOption_CALL
#define com_quantlib_FXOption_CALL 1L
#undef com_quantlib_FXOption_PUT
#define com_quantlib_FXOption_PUT 2L
/*
 * Class:     com_quantlib_FXOption
 * Method:    calculateFXOption
 * Signature: (IDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_quantlib_FXOption_calculateFXOption
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_quantlib_FXOption
 * Method:    calculateFXOptionGreeks
 * Signature: (IDDDDDI)Lcom/quantlib/FXOption/Greeks;
 */
JNIEXPORT jobject JNICALL Java_com_quantlib_FXOption_calculateFXOptionGreeks
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
